### PR TITLE
Feature/analysis id persistence

### PR DESCRIPTION
**Pull request by rtisma**

### CODE REVIEW

**Comment by rtisma** [comment]
ok to test

**Comment by rtisma** [comment]
add to whitelist

**Comment by rtisma** [comment]
test this please

**Comment by rtisma** [comment]
add to whitelist

**Comment by rtisma** [comment]
ok to test

**Comment by rtisma** [comment]
ok to test

**Comment by rtisma** [comment]
ok to test

**Review by andricDu — APPROVED** [review]

**Comment by andricDu** [comment]
Great stuff.

**Pull request merged**
